on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: danimalcontainers.azurecr.io
        username: ${{ secrets.acr_danimalcontainers_username }}
        password: ${{ secrets.acr_danimalcontainers_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/234" -f  "azure" -t danimalcontainers.azurecr.io/pgagic:${{ github.sha }} --label dockerfile-path=azure
        docker push danimalcontainers.azurecr.io/pgagic:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_pgagic_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep pg_agicbe16 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace pg_agicbe16`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: pg_agicbe16
        container-registry-url: danimalcontainers.azurecr.io
        container-registry-username: ${{ secrets.acr_danimalcontainers_username }}
        container-registry-password: ${{ secrets.acr_danimalcontainers_password }}
        secret-name: pgagicdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: pg_agicbe16
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          danimalcontainers.azurecr.io/pgagic:${{ github.sha }}
        imagepullsecrets: |
          pgagicdockerauth
